name: BlockCoins
version: 1.0.0
main: jp.msfblue1.blockcoins.BlockCoins
softdepend: [WorldGuard]
commands:
  rangemine:
    description: ''
  nv:
    description: ''
    aliases: [nightvision]
  blockcoins:
    description: ''
    aliases: [coin,blockcoin]

permissions:
  blockcoins.admin:
      description: Admin permission
      default: op